// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type NewWorry struct {
	Title  string `json:"title"`
	Notes  string `json:"notes"`
	UserID int    `json:"user_id"`
}
