// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name string `json:"name"`
}

type NewWorry struct {
	Text   string `json:"text"`
	UserID string `json:"user_id"`
}
